# Generated by Django 2.2 on 2019-04-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first2lines',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
